# Spring boot application
spring:
  application:
    name: shop-scm-service
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.25.129:3306/pinyougoudb?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root

server:
  port: 8501

# MyBatis Config properties
mybatis:
  type-aliases-package: com.xj.shop.pojo
  mapper-locations: classpath:mapper/*.xml



# Dubbo Config properties
dubbo:
  ## Base packages to scan Dubbo Component：@com.alibaba.dubbo.config.annotation.Service
  scan:
    basePackages: com.xj.shop.service
  ## ApplicationConfig Bean
  application:
    id: shop-scm-service
    name: shop-scm-service
    qos-port: 22222
    qos-enable: true
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
    status: server
    #serialization: kryo
  ## RegistryConfig Bean
  registry:
    id: zookeeper
    address: zookeeper://192.168.25.129:2181

# Enables Dubbo All Endpoints
management:
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
        ## StatusChecker Name extras (default : empty )
        extras: load,threadpool